language: php
php:
- '5.6'
- '7.0'
- '7.1'
services:
    - mongodb
before_script: 
    - composer self-update
    - composer install --prefer-source --no-interaction
script: phpunit
after_success:
  - if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh generate-api.sh; fi